version: "3.7"

services:

  front_end:
    build: ./Front-End
    depends_on:
      - messaging
    command: ["/wait-for-it.sh", "messaging:5672","--strict", "--", "flask", "run", "--host=0.0.0.0"]
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    tty:
      true
    volumes:
      - "./Front-End:/Front-End"
    restart: always

  messaging:
    build: ./Messaging
    ports:
      - 5672:5672 # Default port for RabbitMQ message broker
      - 15672:15672 # Default port for RabbitMQ GUI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  back_end:
    build: ./Back-End
    depends_on:
      - database
      - messaging
    volumes:
     - "./Back-End:/usr/src/myapp"
  database:
    build: ./Database-1
    volumes:
      - "./Database-1/db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
